spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rideprofit
    username: postgres
    password: aluno

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

token:
  secret: chave-temporaria-para-desenvolvimento-mude-em-producao

logging:
  level:
    com.rideprofit: DEBUG
    org.springframework.web: DEBUG
